use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use uuid::Uuid;
use validator::Validate;

#[derive(Debug, Deserialize, Validate, ToSchema)]
pub struct CreateTodoDto {
    /// Name of the todo item
    #[validate(length(min = 1, max = 255))]
    #[schema(example = "Buy groceries")]
    pub name: String,
    /// Optional description
    #[schema(example = "Milk, eggs, bread")]
    pub description: Option<String>,
    /// Whether the todo is completed
    #[schema(example = false)]
    pub completed: Option<bool>,
}

#[derive(Debug, Deserialize, Validate, ToSchema)]
pub struct UpdateTodoDto {
    /// Name of the todo item
    #[validate(length(min = 1, max = 255))]
    #[schema(example = "Buy groceries")]
    pub name: Option<String>,
    /// Optional description
    #[schema(example = "Milk, eggs, bread")]
    pub description: Option<String>,
    /// Whether the todo is completed
    #[schema(example = true)]
    pub completed: Option<bool>,
}

#[derive(Debug, Serialize, Deserialize, ToSchema, selectable_fields::SelectableFields)]
pub struct TodoResponseDto {
    /// Unique identifier
    pub id: Uuid,
    /// Name of the todo item
    pub name: String,
    /// Optional description
    pub description: Option<String>,
    /// Whether the todo is completed
    pub completed: bool,
    /// Creation timestamp
    pub created_at: DateTime<Utc>,
    /// Last update timestamp
    pub updated_at: DateTime<Utc>,
}

impl From<crate::entities::todo::Model> for TodoResponseDto {
    fn from(todo: crate::entities::todo::Model) -> Self {
        Self {
            id: todo.id,
            name: todo.name,
            description: todo.description,
            completed: todo.completed,
            created_at: todo.created_at.naive_utc().and_utc(),
            updated_at: todo.updated_at.naive_utc().and_utc(),
        }
    }
}

// SelectableFields implementation is auto-generated by the derive macro!
