use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use uuid::Uuid;
use validator::Validate;

#[derive(Debug, Deserialize, Validate, ToSchema)]
pub struct CreateUserDto {
    /// Username (3-50 characters)
    #[validate(length(min = 3, max = 50))]
    #[schema(example = "johndoe")]
    pub username: String,
    /// Email address
    #[validate(email)]
    #[schema(example = "john@example.com")]
    pub email: String,
    /// Password (minimum 8 characters)
    #[validate(length(min = 8))]
    #[schema(example = "securepassword123")]
    pub password: String,
}

#[derive(Debug, Deserialize, Validate, ToSchema)]
pub struct UpdateUserDto {
    /// Username (3-50 characters)
    #[validate(length(min = 3, max = 50))]
    #[schema(example = "johndoe")]
    pub username: Option<String>,
    /// Email address
    #[validate(email)]
    #[schema(example = "john@example.com")]
    pub email: Option<String>,
    /// Password (minimum 8 characters)
    #[validate(length(min = 8))]
    #[schema(example = "newsecurepassword123")]
    pub password: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, ToSchema, selectable_fields::SelectableFields)]
pub struct UserResponseDto {
    /// Unique identifier
    pub id: Uuid,
    /// Username
    pub username: String,
    /// Email address
    /// To require authentication for email, add: #[field(role = "user")]
    pub email: String,
    /// Creation timestamp
    pub created_at: DateTime<Utc>,
    /// Last update timestamp
    pub updated_at: DateTime<Utc>,
}

impl From<crate::entities::user::Model> for UserResponseDto {
    fn from(user: crate::entities::user::Model) -> Self {
        Self {
            id: user.id,
            username: user.username,
            email: user.email,
            created_at: user.created_at.naive_utc().and_utc(),
            updated_at: user.updated_at.naive_utc().and_utc(),
        }
    }
}

// SelectableFields implementation is auto-generated by the derive macro!
// Example usage with role-based access:
//
// #[derive(SelectableFields)]
// pub struct UserResponseDto {
//     pub id: Uuid,
//     pub username: String,
//     #[field(role = "user")]  // Requires authentication
//     pub email: String,
//     #[field(skip)]  // Never exposed
//     password_hash: String,
// }
