[package]
name = "api_resource"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = { workspace = true }
pluralizer = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
proc_macros = { workspace = true, features = ["api_resource"] }
trybuild = { workspace = true }

[[test]]
name = "tests"
path = "tests/progress.rs"
